'use strict';

(() => {
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const GENRES = ['Best Sellers','Fantasy','Mystery & Thrillers','Science Fiction','Romance','Horror','Biography & Memoir','History','Business','Self-Development','True Crime','Comedy'];

  const state = {
    books:new Map(), playback:new Map(), pending:new Map(),
    detailBook:null, playingBook:null, currentPlayback:null, currentChapter:0,
    searchTimer:null, sleepTimer:null, lastSave:0
  };

  const store = {
    get(k,f){try{return JSON.parse(localStorage.getItem(`audiobox:v3:${k}`))??f}catch{return f}},
    set(k,v){try{localStorage.setItem(`audiobox:v3:${k}`,JSON.stringify(v))}catch{}},
    favorites(){return this.get('favorites',[])},
    toggleFavorite(id){const key=String(id),a=this.favorites().filter(Boolean),i=a.indexOf(key);if(i>=0)a.splice(i,1);else a.unshift(key);this.set('favorites',a.slice(0,100));return i<0},
    recent(){return this.get('recent',[])},
    touchRecent(id){const key=String(id),a=this.recent().filter(x=>String(x)!==key);a.unshift(key);this.set('recent',a.slice(0,40))},
    progress(){return this.get('progress',{})},
    saveProgress(id,v){const a=this.progress();a[String(id)]={...(a[String(id)]||{}),...v,updatedAt:Date.now()};this.set('progress',a)},
    snapshots(){return this.get('snapshots',{})},
    remember(book){if(!book?.id)return;const a=this.snapshots();a[String(book.id)]={...book,description:String(book.description||'').slice(0,2400),savedAt:Date.now()};this.set('snapshots',Object.fromEntries(Object.entries(a).sort((x,y)=>(y[1]?.savedAt||0)-(x[1]?.savedAt||0)).slice(0,150)))}
  };

  const esc = (v='') => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function strip(v=''){const d=document.createElement('div');d.innerHTML=String(v);return(d.textContent||'').replace(/\s+/g,' ').trim()}
  function author(b){return b?.authors?.filter(Boolean).join(', ')||'Unknown author'}
  function narrator(b){return b?.narrators?.filter(Boolean).join(', ')||''}
  function fmt(sec){if(!Number.isFinite(sec)||sec<0)return'0:00';sec=Math.floor(sec);const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
  function runtime(b){const n=Number(b?.durationMinutes||0);if(!n)return'';const h=Math.floor(n/60),m=Math.round(n%60);return h?`${h}h ${m}m`:`${m}m`}
  function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2400)}

  function remember(books){for(const b of books||[]){if(!b?.id)continue;state.books.set(String(b.id),b);store.remember(b)}return books||[]}
  function restore(){for(const [id,b] of Object.entries(store.snapshots()))if(b?.id)state.books.set(String(id),b)}

  async function api(params={}){
    const qs=new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined&&v!==null&&v!==''));
    const r=await fetch(`/api/catalog?${qs}`);const data=await r.json().catch(()=>({}));
    if(!r.ok)throw new Error(data.error||data.detail||`Catalog request failed (${r.status})`);return data;
  }

  async function getBook(id){
    const key=String(id),cached=state.books.get(key);
    if(cached?.source==='archive')return cached;
    if(cached && !/^[A-Z0-9]{10}$/i.test(key))return cached;
    try{const {book}=await api({mode:'book',asin:key});if(book)return remember([book])[0]}catch(e){if(cached)return cached;throw e}
    return cached||null;
  }

  function fallback(b){return `<div class="cover-fallback"><strong>${esc(b.title)}</strong><span>${esc(author(b))}</span></div>`}
  function progressPct(b){const p=store.progress()[String(b.id)],total=Number(p?.bookDuration||(b.durationMinutes||0)*60);return p&&total?Math.max(0,Math.min(100,Number(p.absoluteTime||0)/total*100)):0}
  function card(b){const p=progressPct(b),rating=Number(b.rating||0);const chip=b.playbackIdentifier?'▶ PLAY NOW':rating?`★ ${rating.toFixed(1)}`:'AUDIOBOOK';return `<button class="card catalog-card" data-book-id="${esc(b.id)}" aria-label="${esc(b.title)}">${fallback(b)}${b.cover?`<img src="${esc(b.cover)}" alt="Cover of ${esc(b.title)}" loading="lazy" referrerpolicy="no-referrer" />`:''}<div class="catalog-chip">${chip}</div><div class="card-overlay"><strong>${esc(b.title)}</strong><span>${esc(author(b))}</span></div>${p?`<div class="progress-line"><i style="width:${p.toFixed(1)}%"></i></div>`:''}</button>`}
  const skeletons=(n=10)=>Array.from({length:n},()=>'<div class="card skeleton"></div>').join('');
  const row=(name,books)=>books?.length?`<section class="row"><div class="row-head"><h2>${esc(name)}</h2></div><div class="rail">${books.map(card).join('')}</div></section>`:'';
  function bindCards(root=document){$$('[data-book-id]',root).forEach(e=>e.addEventListener('click',()=>openDetails(e.dataset.bookId)))}

  function hero(b){const meta=[author(b),runtime(b),b.rating?`★ ${Number(b.rating).toFixed(1)}`:''].filter(Boolean).join(' · ');return `<section class="hero netflix-hero" data-hero-id="${esc(b.id)}"><div class="hero-bg" ${b.cover?`style="background-image:url('${esc(b.cover)}')"`:''}></div><div class="hero-content"><div class="eyebrow"><span class="n-mark">A</span> READY TO PLAY</div><h1>${esc(b.title)}</h1><div class="hero-author">${esc(meta)}</div><p class="hero-desc">${esc(strip(b.description||b.subtitle||'Press play to start listening.'))}</p><div class="hero-actions"><button class="btn primary" data-hero-play>▶ Play</button><button class="btn secondary" data-hero-info>ⓘ More Info</button></div></div></section>`}

  async function renderHome(){
    const view=$('#homeView');view.innerHTML=`<section class="hero netflix-hero loading-hero"><div class="hero-bg"></div><div class="hero-content"><div class="eyebrow">AUDIOBOX</div><h1>Loading…</h1><p class="hero-desc">Loading playable audiobooks.</p></div></section><div class="content-rows"><section class="row"><div class="row-head"><h2>Loading</h2></div><div class="rail">${skeletons()}</div></section></div>`;
    try{
      const data=await api({mode:'home'});const all=(data.rows||[]).flatMap(r=>r.books||[]);remember(all);if(data.hero)remember([data.hero]);
      const progress=store.progress();const cont=Object.keys(progress).sort((a,b)=>(progress[b]?.updatedAt||0)-(progress[a]?.updatedAt||0)).map(id=>state.books.get(id)).filter(Boolean).slice(0,18);
      const recent=store.recent().map(id=>state.books.get(String(id))).filter(Boolean).slice(0,18);const fav=store.favorites().map(id=>state.books.get(String(id))).filter(Boolean).slice(0,18);
      const rows=[...(cont.length?[{name:'Continue Listening',books:cont}]:[]),...(recent.length?[{name:'Recently Played',books:recent}]:[]),...(data.rows||[]),...(fav.length?[{name:'My List',books:fav}]:[])];
      const hb=data.hero||rows.flatMap(r=>r.books||[])[0];view.innerHTML=`${hb?hero(hb):''}<div class="content-rows">${rows.map(r=>row(r.name,r.books)).join('')}</div>`;bindCards(view);
      const he=$('[data-hero-id]',view);$('[data-hero-info]',he)?.addEventListener('click',()=>openDetails(hb.id));$('[data-hero-play]',he)?.addEventListener('click',()=>playBook(hb.id));
      prefetchPlayable([hb,...all].filter(Boolean).slice(0,10));
    }catch(e){view.innerHTML=errorBox('The library could not be loaded',e.message)}
  }

  function errorBox(t,m){return `<div class="error-box"><h2>${esc(t)}</h2><p>${esc(m||'Try again in a moment.')}</p><button class="btn secondary" onclick="location.reload()">Retry</button></div>`}
  function renderBrowse(){const v=$('#browseView');v.innerHTML=`<div class="browse-hero"><h1>Browse</h1><p class="subtext">Explore the full audiobook catalog. Titles marked Play Now have confirmed AudioBox playback.</p><div class="genre-pills">${GENRES.map(g=>`<button class="pill" data-genre="${esc(g)}">${esc(g)}</button>`).join('')}</div></div><div id="browseBody"><div class="grid">${skeletons(18)}</div></div>`;$$('.pill',v).forEach(b=>b.addEventListener('click',()=>loadGenre(b.dataset.genre,b)));loadGenre('Best Sellers',$('.pill',v))}
  async function loadGenre(name,button){$$('.pill',$('#browseView')).forEach(x=>x.classList.toggle('active',x===button));const body=$('#browseBody');body.innerHTML=`<div class="grid">${skeletons(18)}</div>`;try{const {books}=await api({mode:'genre',genre:name==='Best Sellers'?'':name,limit:50});remember(books);body.innerHTML=books?.length?`<div class="grid">${books.map(card).join('')}</div>`:'<div class="empty"><strong>No titles found.</strong>Try another shelf.</div>';bindCards(body)}catch(e){body.innerHTML=errorBox(`Couldn't load ${name}`,e.message)}}
  async function renderMyList(){const v=$('#myListView');const ids=store.favorites();const books=ids.map(id=>state.books.get(String(id))).filter(Boolean);v.innerHTML=`<div class="list-hero"><h1>My List</h1><p class="subtext">Saved on this device.</p></div>${books.length?`<div class="grid">${books.map(card).join('')}</div>`:'<div class="empty"><strong>Your list is empty.</strong>Add titles with the + button.</div>'}`;bindCards(v)}

  function detailMarkup(b){const fav=store.favorites().includes(String(b.id)),series=b.series?.map(s=>`${s.name}${s.position?` #${s.position}`:''}`).join(', ')||'',meta=[author(b),runtime(b),b.releaseDate?.slice(0,4),b.rating?`★ ${Number(b.rating).toFixed(1)}`:''].filter(Boolean).join(' · ');return `<section class="detail-hero modern-detail"><div class="detail-hero-bg" ${b.cover?`style="background-image:url('${esc(b.cover)}')"`:''}></div><div class="detail-hero-copy"><div class="eyebrow">AUDIOBOX</div><h2 id="detailTitle">${esc(b.title)}</h2>${b.subtitle?`<div class="detail-subtitle">${esc(b.subtitle)}</div>`:''}<div class="detail-sub">${esc(meta)}</div><div class="detail-actions"><button class="btn primary" data-detail-play disabled>Checking playback…</button><button class="circle-btn ${fav?'active':''}" data-favorite>${fav?'✓':'+'}</button></div></div></section><section class="detail-body"><div class="detail-description">${esc(strip(b.description)||'No description is available for this title.')}</div><div class="meta-list"><div><b>Author:</b> ${esc(author(b))}</div>${narrator(b)?`<div><b>Narrated by:</b> ${esc(narrator(b))}</div>`:''}${series?`<div><b>Series:</b> ${esc(series)}</div>`:''}${b.genres?.length?`<div><b>Genres:</b> ${esc(b.genres.slice(0,6).join(', '))}</div>`:''}${b.publisher?`<div><b>Publisher:</b> ${esc(b.publisher)}</div>`:''}</div></section><section class="playback-zone" data-playback-zone><div class="playback-check"><div class="loader"></div><div><strong>Finding playback</strong><span>Checking AudioBox sources…</span></div></div></section>`}

  async function openDetails(id){const modal=$('#modalBackdrop'),content=$('#detailContent');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';content.innerHTML='<div style="min-height:500px;display:grid;place-items:center"><div class="loader"></div></div>';try{const b=await getBook(id);if(!b)throw new Error('Book metadata unavailable.');state.detailBook=b;content.innerHTML=detailMarkup(b);$('[data-favorite]',content)?.addEventListener('click',e=>{const on=store.toggleFavorite(b.id);e.currentTarget.textContent=on?'✓':'+';e.currentTarget.classList.toggle('active',on);toast(on?'Added to My List':'Removed from My List')});$('[data-detail-play]',content)?.addEventListener('click',()=>playBook(b.id));const p=await resolvePlayback(b);if(state.detailBook?.id===b.id)renderPlayback(b,p)}catch(e){content.innerHTML=errorBox('Could not open this audiobook',e.message)}}

  function renderPlayback(b,p){const zone=$('[data-playback-zone]',$('#detailContent')),play=$('[data-detail-play]',$('#detailContent'));if(!zone||!play)return;if(!p?.sections?.length){play.disabled=true;play.textContent='Playback not available yet';zone.innerHTML='<div class="playback-unavailable"><strong>No confirmed playback source yet.</strong><span>This title stays searchable while AudioBox keeps expanding playback coverage.</span></div>';return}play.disabled=false;play.textContent=`▶ ${store.progress()[String(b.id)]?'Resume':'Play'}`;zone.innerHTML=`<div class="chapters"><div class="chapters-head"><h3>${p.sections.length} chapters</h3><span>${esc(p.provider||'AudioBox playback')}</span></div><div class="chapter-list">${p.sections.map((s,i)=>`<button class="chapter" data-chapter-index="${i}"><span class="chapter-num">${i+1}</span><span><strong>${esc(s.title)}</strong><small>${esc(s.fileName||'')}</small></span><span class="chapter-time">${s.duration?fmt(s.duration):''}</span></button>`).join('')}</div></div>`;$$('[data-chapter-index]',zone).forEach(btn=>btn.addEventListener('click',()=>startPlayback(b,p,Number(btn.dataset.chapterIndex),false)))}

  async function fetchPlayback(b){const q=new URLSearchParams();q.set('title',b.title||'');q.set('author',author(b));if(b.durationMinutes)q.set('duration',String(b.durationMinutes));if(b.asin)q.set('asin',b.asin);if(b.playbackIdentifier)q.set('identifier',b.playbackIdentifier);const r=await fetch(`/api/playback?${q}`,{headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));return d.available&&d.playback?d.playback:{sections:[]}}
  function resolvePlayback(b){const id=String(b.id);if(state.playback.has(id))return Promise.resolve(state.playback.get(id));if(state.pending.has(id))return state.pending.get(id);const task=fetchPlayback(b).then(p=>{state.playback.set(id,p);return p}).catch(()=>{const p={sections:[]};state.playback.set(id,p);return p}).finally(()=>state.pending.delete(id));state.pending.set(id,task);return task}
  function prefetchPlayable(books){const q=[...new Map(books.filter(b=>b?.id).map(b=>[String(b.id),b])).values()];let active=0;const pump=()=>{while(active<2&&q.length){const b=q.shift();if(state.playback.has(String(b.id))||state.pending.has(String(b.id)))continue;active++;resolvePlayback(b).finally(()=>{active--;setTimeout(pump,80)})}};pump()}

  function playBook(id){const key=String(id),b=state.books.get(key);if(b&&state.playback.has(key)){const p=state.playback.get(key);if(p?.sections?.length){const prog=store.progress()[key];startPlayback(b,p,Math.min(Number(prog?.chapterIndex||0),p.sections.length-1),true);return}toast('No playback source for this title yet.');return}prepareAndPlay(key)}
  async function prepareAndPlay(id){const b=await getBook(id).catch(()=>state.books.get(String(id))||null);if(!b)return toast('Could not load this title.');toast('Finding playback…');const p=await resolvePlayback(b);if(!p?.sections?.length){toast('No playback source for this title yet.');if(!$('#modalBackdrop').classList.contains('open'))openDetails(b.id);return}const prog=store.progress()[String(b.id)];startPlayback(b,p,Math.min(Number(prog?.chapterIndex||0),p.sections.length-1),true)}

  function startPlayback(b,p,index=0,resume=true){const audio=$('#audio'),s=p.sections[index];if(!s)return;state.playingBook=b;state.currentPlayback=p;state.currentChapter=index;store.touchRecent(b.id);audio.src=s.url;audio.playbackRate=Number($('#speedBtn').dataset.speed||1);$('#player').classList.add('show');$('#player').setAttribute('aria-hidden','false');$('#playerTitle').textContent=b.title;$('#playerChapter').textContent=s.title;$('#playerCover').src=b.cover||'';$('#playerCover').alt=b.title;const old=store.progress()[String(b.id)];const restore=()=>{if(resume&&old&&Number(old.chapterIndex)===index&&Number(old.time)>0&&Number.isFinite(audio.duration)&&Number(old.time)<audio.duration-5)audio.currentTime=Number(old.time)};audio.addEventListener('loadedmetadata',restore,{once:true});audio.load();const promise=audio.play();if(promise?.catch)promise.catch(err=>{console.warn('AudioBox play failed',err);toast(err?.name==='NotAllowedError'?'Ready — tap ▶ to start':'Audio failed to start. Tap ▶ to retry.')});updateMediaSession(b,s);updatePlayingChapter()}
  function updateMediaSession(b,s){if(!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:s.title||b.title,artist:author(b),album:b.title,artwork:b.cover?[{src:b.cover,sizes:'512x512'}]:[]})}catch{}}
  function updatePlayingChapter(){$$('[data-chapter-index]',$('#detailContent')).forEach(e=>e.classList.toggle('playing',Number(e.dataset.chapterIndex)===state.currentChapter))}
  function absoluteProgress(){if(!state.currentPlayback)return 0;return state.currentPlayback.sections.slice(0,state.currentChapter).reduce((n,s)=>n+Number(s.duration||0),0)+Number($('#audio').currentTime||0)}
  function fullDuration(){return state.currentPlayback?.sections?.reduce((n,s)=>n+Number(s.duration||0),0)||(state.playingBook?.durationMinutes||0)*60}
  function saveProgress(force=false){const a=$('#audio'),b=state.playingBook;if(!b||!state.currentPlayback?.sections?.length)return;const now=Date.now();if(!force&&now-state.lastSave<5000)return;state.lastSave=now;store.saveProgress(b.id,{chapterIndex:state.currentChapter,time:a.currentTime||0,absoluteTime:absoluteProgress(),bookDuration:fullDuration()})}
  function nextChapter(delta){if(!state.currentPlayback||!state.playingBook)return;const n=state.currentChapter+delta;if(n<0||n>=state.currentPlayback.sections.length)return;saveProgress(true);startPlayback(state.playingBook,state.currentPlayback,n,false)}

  function closeModal(){$('#modalBackdrop').classList.remove('open');$('#modalBackdrop').setAttribute('aria-hidden','true');document.body.style.overflow=''}
  function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name==='mylist'?'myList':name}View`));$$('.navlink').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='browse')renderBrowse();if(name==='mylist')renderMyList();window.scrollTo({top:0,behavior:'smooth'})}

  function initSearch(){const panel=$('#searchPanel'),input=$('#searchInput'),results=$('#searchResults'),meta=$('#searchMeta');const open=()=>{panel.classList.add('open');panel.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),60)},close=()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true');input.blur()};$('#searchToggle').addEventListener('click',open);$('#searchClose').addEventListener('click',close);input.addEventListener('input',()=>{clearTimeout(state.searchTimer);const q=input.value.trim();if(q.length<2){meta.textContent='Search the AudioBox catalog';results.innerHTML='';return}meta.textContent='Searching…';results.innerHTML=skeletons(12);state.searchTimer=setTimeout(async()=>{try{const {books}=await api({mode:'search',q,limit:40});remember(books);meta.textContent=`${books.length} result${books.length===1?'':'s'} for “${q}”`;results.innerHTML=books.length?books.map(card).join(''):'<div class="empty"><strong>No matches.</strong>Try another title or author.</div>';bindCards(results)}catch(e){meta.textContent=e.message;results.innerHTML=''}},300)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(panel.classList.contains('open'))close();else if($('#modalBackdrop').classList.contains('open'))closeModal()}})}

  function initPlayer(){const audio=$('#audio'),play=$('#playToggle'),seek=$('#seek'),volume=$('#volume'),speed=$('#speedBtn'),sleep=$('#sleepBtn');play.addEventListener('click',()=>audio.paused?audio.play().catch(()=>toast('Audio could not start.')):audio.pause());$('#prevChapter').addEventListener('click',()=>nextChapter(-1));$('#nextChapter').addEventListener('click',()=>nextChapter(1));$('#playerExpand').addEventListener('click',()=>state.playingBook&&openDetails(state.playingBook.id));audio.addEventListener('play',()=>play.textContent='❚❚');audio.addEventListener('pause',()=>{play.textContent='▶';saveProgress(true)});audio.addEventListener('error',()=>toast('That audio source failed. Try another title.'));audio.addEventListener('timeupdate',()=>{$('#currentTime').textContent=fmt(audio.currentTime);$('#duration').textContent=fmt(audio.duration);if(Number.isFinite(audio.duration)&&audio.duration>0)seek.value=String(Math.round(audio.currentTime/audio.duration*1000));saveProgress(false)});audio.addEventListener('durationchange',()=>$('#duration').textContent=fmt(audio.duration));audio.addEventListener('ended',()=>state.currentPlayback&&state.currentChapter<state.currentPlayback.sections.length-1?nextChapter(1):saveProgress(true));seek.addEventListener('input',()=>{if(Number.isFinite(audio.duration)&&audio.duration>0)audio.currentTime=Number(seek.value)/1000*audio.duration});volume.addEventListener('input',()=>audio.volume=Number(volume.value));audio.volume=Number(volume.value);const speeds=[1,1.25,1.5,1.75,2,.75];speed.dataset.speed='1';speed.addEventListener('click',()=>{const cur=Number(speed.dataset.speed||1),n=speeds[(speeds.indexOf(cur)+1)%speeds.length];speed.dataset.speed=String(n);speed.textContent=`${n}×`;audio.playbackRate=n});const opts=[0,15,30,45,60];let si=0;sleep.addEventListener('click',()=>{si=(si+1)%opts.length;const min=opts[si];clearTimeout(state.sleepTimer);if(!min){sleep.textContent='☾';toast('Sleep timer off')}else{sleep.textContent=`${min}m`;state.sleepTimer=setTimeout(()=>{audio.pause();sleep.textContent='☾';si=0;toast('Sleep timer finished')},min*60000);toast(`Sleep timer: ${min} minutes`)}});if('mediaSession'in navigator){navigator.mediaSession.setActionHandler?.('play',()=>audio.play());navigator.mediaSession.setActionHandler?.('pause',()=>audio.pause());navigator.mediaSession.setActionHandler?.('previoustrack',()=>nextChapter(-1));navigator.mediaSession.setActionHandler?.('nexttrack',()=>nextChapter(1))}}

  function initNav(){$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.nav)));$('#modalClose').addEventListener('click',closeModal);$('#modalBackdrop').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});window.addEventListener('scroll',()=>$('#topbar').classList.toggle('scrolled',window.scrollY>35),{passive:true})}
  function init(){restore();initNav();initSearch();initPlayer();renderHome();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}
  window.addEventListener('beforeunload',()=>saveProgress(true));window.addEventListener('DOMContentLoaded',init);
})();
